import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import Layout from '../components/Layout'

export default function Home() {

    return (
        <Layout>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to the main page
                </h1>

                <Link href="/login" passHref>
                    <button className={styles.button} href="/discover">
                        Discover</button>
                </Link>


            </main>

        </Layout>
    )
}

